version: '3.8'

services:
  v2ray:
    image: teddysun/v2ray:4.39.1
    restart: unless-stopped
    volumes:
      - ./v2ray:/etc/v2ray
    ports:
     - "127.0.0.1:1080:1080"
     - "127.0.0.1:12306:12306"
